PINECONE_API_TOKEN="pcsk_4Yt6LT_7P91zXS9PHfZUWvCTHdxg1wMPid6H4A82Aj1EuSTq6qFghStsrSE5iiqBCJHZ7h"

OPENAI_PROXY_KEY="sk-rVlnz2fmm4mV7IIQeRGydXZ4THD0ZmEtkcEOnIRn3P4fxxkm"

BASE_URL="https://chat.cloudapi.vip/v1"